"""empty message

Revision ID: 15920c5ead83
Revises: 2f349bf10bd4
Create Date: 2023-07-14 18:11:57.165850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15920c5ead83'
down_revision = '2f349bf10bd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
