"""empty message

Revision ID: cb9ce1cd26ff
Revises: 
Create Date: 2023-07-13 09:33:53.056238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb9ce1cd26ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('twitch_id', sa.Integer(), nullable=True),
    sa.Column('twitch_username', sa.String(), nullable=True),
    sa.Column('discord_id', sa.Integer(), nullable=True),
    sa.Column('discord_username', sa.String(), nullable=True),
    sa.Column('verus', sa.String(), nullable=True),
    sa.Column('eth', sa.Integer(), nullable=True),
    sa.Column('rental', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('airdrop_amount', sa.Integer(), nullable=True),
    sa.Column('discord_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
